[package]
name = "flaty"
version = "0.0.1"
edition = "2021"
authors = ["Yann Villessuzanne"]
description = "Flat-File CMS"
license = "MIT"
repository = "https://github.com/linfir/flaty"
keywords = ["http", "web", "server", "cms"]

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
handlebars = "4.3.6"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["server", "http1"] }
mime_guess = "2.0.4"
pulldown-cmark = "0.9.2"
rsass = "0.27.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "net", "fs", "io-util"] }
toml = "0.7.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
twox-hash = "1.6.3"
