[package]
name = "flaty"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
axum = "0.6.12"
clap = { version = "4.2.1", features = ["derive"] }
handlebars = "4.3.6"
pulldown-cmark = { version = "0.9.2", default-features = false }
rsass = "0.27.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
yaml-rust = "0.4.5"
